### ISSUE TITLE
File "/usr/local/bin/bvg-grabber.py", line 65  SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by keks1337** [MarkusH/bvg-grabber#14]
Hi 
tested it on raspberry but doesnt work 

```
$bvg-grabber.py "U Ernst-Reuter-Platz (Berlin)" - --vehicle U --limit 2 | json_pp
  File "/usr/local/bin/bvg-grabber.py", line 65
    print(res.to_json, file=file)
                           ^
SyntaxError: invalid Syntax
malformed JSON string, neither array, object, number, string or atom, at character offset 0 (before "(end of string)") at /usr/bin/json_pp line 45.
```

any ideas?

**Comment by cstruck** [comment]
which version of python are you using?

**Comment by keks1337** [comment]
I used 2.7. now i have changed to 3.5 and have another error:

` bvg-grabber.py --help
Traceback (most recent call last):
  File "/usr/local/bin/bvg-grabber.py", line 7, in <module>
    from bvggrabber.api.actualdeparture import ActualDepartureQueryApi
ImportError: No module named 'bvggrabber'
`

**Comment by cstruck** [comment]
How did you install bvg-grabber? It seems that the api files are not in the python path nor in the same folder.

**Comment by gpcf** [comment]
can also confirm this bug, I installed bvg-grabber with pip

**Comment by MarkusH** [comment]
Did you use `pip install` or `pip3 install`?

**Comment by gpcf** [comment]
pip install

**Comment by MarkusH** [comment]
bvg-grabber only supports Python 3. In fact, from version 0.2.0 onward, only Python 3.4, 3.6, 3.7, and 3.8.
